import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import '@/styles/globals.css';
import '@/styles/theme.css';
import Header from "@/components/Header";
import { pfdinTextPro } from "@/assets/fonts";



export const metadata: Metadata = {
  title: "SKY - Cliente Autorizado ATN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${pfdinTextPro.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
